name: Installing Dependencies

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm install
          npm install @vitejs/plugin-react@latest
          npm ls @vitejs/plugin-react
