name: Installing Dependencies

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Navigate to backend directory
        run: |
          cd ./crud-backend
          npm install

      - name: Navigate to frontend directory
        run: |
          cd ./crud-frontend
          npm install
          npm install @vitejs/plugin-react@latest
          npm ls @vitejs/plugin-react
